name: Build and Deploy React App

# Triggers the workflow on push or pull request events to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Environment setup and job steps
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository's code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Specify your Node.js version

      # Install dependencies and build
      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      # Deploy the build folder to a deployment service
      # This example uses GitHub Pages, adjust for your deployment service
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build  # This should match your build output folder
